# Generated by Django 3.0.8 on 2020-07-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WFB_Army', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.IntegerField()),
                ('cp_used_before_battle', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=64)),
                ('score_no_details', models.BooleanField()),
                ('score_p1', models.IntegerField()),
                ('score_p2', models.IntegerField()),
                ('army_p1_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_p1_ids', to='WFB_Army.Army')),
                ('army_p2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_p2_ids', to='WFB_Army.Army')),
            ],
        ),
        migrations.CreateModel(
            name='MatchLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField()),
                ('primary_score', models.IntegerField()),
                ('secondary1_score', models.IntegerField()),
                ('secondary2_score', models.IntegerField()),
                ('secondary3_score', models.IntegerField()),
                ('other_score', models.IntegerField()),
                ('cp_used', models.IntegerField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_ids', to='WFB_Match.Match')),
            ],
        ),
    ]
