# Generated by Django 3.0.8 on 2020-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='cp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='cp_used_before_battle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_p1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_p2',
            field=models.IntegerField(blank=True),
        ),
    ]
