# Generated by Django 3.0.8 on 2020-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Match', '0004_auto_20200729_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='cp',
            new_name='cp_p1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='cp_used_before_battle',
            new_name='cp_p1_used_before_battle',
        ),
        migrations.AddField(
            model_name='match',
            name='cp_p2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='cp_p2_used_before_battle',
            field=models.IntegerField(default=0),
        ),
    ]
