# Generated by Django 3.0.8 on 2020-07-29 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WFB_Match', '0005_auto_20200729_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_p1_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_p2_ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
