# Generated by Django 3.0.8 on 2020-07-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Match', '0006_auto_20200729_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='point_limit',
            field=models.IntegerField(default=2000),
        ),
    ]
