# Generated by Django 3.0.8 on 2020-07-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Match', '0007_match_point_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='point_limit',
        ),
    ]
