# Generated by Django 3.0.8 on 2020-07-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Match', '0009_auto_20200730_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchline',
            name='match_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_ids', to='WFB_Match.Match'),
        ),
    ]
