# Generated by Django 3.0.8 on 2020-07-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Match', '0011_auto_20200731_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
    ]
