# Generated by Django 3.0.8 on 2020-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Match', '0014_auto_20200804_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_p1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_p2',
            field=models.IntegerField(default=0),
        ),
    ]
