# Generated by Django 3.0.8 on 2020-08-07 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Match', '0015_auto_20200807_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 7)),
        ),
    ]
