# Generated by Django 3.0.8 on 2020-08-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_ArmyList', '0002_armylist_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armylist',
            name='shortDescription',
        ),
    ]
