# Generated by Django 3.0.8 on 2020-07-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StratagemPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Stratagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('type', models.CharField(max_length=64)),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stratagem_ids', to='WFB_Stratagem.StratagemPhase')),
            ],
        ),
    ]
