# Generated by Django 3.0.8 on 2020-07-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Army', '0001_initial'),
        ('WFB_Stratagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagem',
            name='army',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stratagem_ids', to='WFB_Army.Army'),
        ),
    ]
