# Generated by Django 3.0.8 on 2020-07-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Stratagem', '0002_stratagem_army'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stratagem',
            old_name='army',
            new_name='army_id',
        ),
        migrations.RenameField(
            model_name='stratagem',
            old_name='phase',
            new_name='phase_id',
        ),
    ]
