# Generated by Django 3.0.8 on 2020-08-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Army', '0001_initial'),
        ('WFB_Stratagem', '0004_auto_20200802_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratagem',
            name='army_id',
            field=models.ForeignKey(db_column='army_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stratagem_ids', to='WFB_Army.Army'),
        ),
        migrations.AlterField(
            model_name='stratagem',
            name='phase_id',
            field=models.ForeignKey(db_column='phase_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stratagem_ids', to='WFB_Stratagem.StratagemPhase'),
        ),
    ]
