# Generated by Django 3.0.8 on 2020-07-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WFB_Army', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('army_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_ids', to='WFB_Army.Army')),
                ('unit_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_ids', to='WFB_Unit.UnitType')),
            ],
        ),
    ]
