# Generated by Django 3.0.8 on 2020-07-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Scenario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='deployment',
            field=models.ImageField(default=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='rules',
            field=models.ImageField(default=True, null=True, upload_to=''),
        ),
    ]
