# Generated by Django 3.0.8 on 2020-07-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Scenario', '0003_auto_20200730_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='deployment',
            field=models.ImageField(default=True, null=True, upload_to=''),
        ),
    ]
