# Generated by Django 3.0.8 on 2020-08-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WFB_Scenario', '0004_auto_20200731_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='type_id',
            field=models.ForeignKey(db_column='type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_ids', to='WFB_Scenario.ScenarioType'),
        ),
    ]
